TicketReseller/TicketReseller.WebUI/Areas/Admin/Controllers/CityManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TicketReseller.Data.Context;
using TicketReseller.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TicketReseller.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CityManagementController : Controller
    {
        private UnitOfWork _unitOfWork;
        private readonly IStringLocalizer<CityManagementController> localizer;


        public CityManagementController(IStringLocalizer<CityManagementController> localizer, UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            this.localizer = localizer;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            var cities = _unitOfWork.CityRepository.Get();
            return View(cities);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(City city)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _unitOfWork.CityRepository.Insert(city);
                    _unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DbUpdateException /* dex */)
            {
                ModelState.AddModelError(string.Empty, localizer["Unable to save changes. Try again, and if the problem persists contact your system administrator."]);
            }
            return View(city);
        }

        public ActionResult Edit(int id)
        {
            var city = _unitOfWork.CityRepository.GetByID(id);

            if (city == null)
            {
                return RedirectToAction("Index");
            }
            return View(city);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(City city)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _unitOfWork.CityRepository.Update(city);
                    _unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DbUpdateException /* dex */)
            {
                ModelState.AddModelError(string.Empty, localizer["Unable to save changes. Try again, and if the problem persists contact your system administrator."]);
            }
            return View(city);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                var city = _unitOfWork.CityRepository.GetByID(id);

                if (city == null)
                {
                    return RedirectToAction("Index");
                }
                _unitOfWork.CityRepository.Delete(id);
                _unitOfWork.Save();
            }
            catch (DbUpdateException /* dex */)
            {
                ViewData["ErrorMessage"] =
                    localizer["Delete failed. Try again, and if the problem persists " +
                    "see your system administrator."];
            }
            return RedirectToAction("Index");
        }
    }
}

TicketReseller/TicketReseller.WebUI/Areas/Admin/Views/CityManagement/Create.cshtml
@model City
@{
    ViewData["Title"] = "Create";
}
@section OptionsSideMenu {
    <div class="col-md-3">
        @{await Html.RenderPartialAsync("_AdminOptionsPartial");}
    </div>
}
<div class="col-md-6">
    <h2>@Localizer["Creation city"]</h2>
    <hr />
    <p class="text-danger">@ViewData["ErrorMessage"]</p>
    <form asp-action="Create">
        <div class="form-horizontal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            </br>
            <div class="form-group pull-right">
                <div class="col-md-10">
                    <input type="submit" value="@Localizer["Create"]" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </form>
    <div>
        <a asp-action="Index">@Localizer["Back to List"]</a>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("/Areas/Main/Views/Shared/_ValidationScriptsPartial.cshtml");}
}

TicketReseller/TicketReseller.WebUI/Areas/Admin/Views/CityManagement/Edit.cshtml
@model City
@{
    ViewData["Title"] = "Edit";
}
@section OptionsSideMenu {
    <div class="col-md-3">
        @{await Html.RenderPartialAsync("_AdminOptionsPartial");}
    </div>
}
<div class="col-md-6">
    <h2>@Localizer["Editing city"]</h2>
    <hr />
    <p class="text-danger">@ViewData["ErrorMessage"]</p>
    <form asp-action="Edit">
        <div class="form-horizontal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            </br>
            <div class="form-group pull-right">
                <div class="col-md-10">
                    <input type="submit" value="@Localizer["Update"]" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </form>
    <div>
        <a asp-action="Index">@Localizer["Back to List"]</a>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("/Areas/Main/Views/Shared/_ValidationScriptsPartial.cshtml");}
}

TicketReseller/TicketReseller.WebUI/Areas/Admin/Views/CityManagement/Index.cshtml
@model List<City>
@section OptionsSideMenu {
    <div class="col-md-3">
        @{await Html.RenderPartialAsync("_AdminOptionsPartial");}
    </div>
}
<div class="col-md-9">
    <row>
        <div class="col-md-12">
            <h1>
                <small>@Localizer["Cities"]</small>
                <a class="btn btn-primary pull-right" role="button" asp-action="Create" asp-controller="CityManagement">
                    <span class="glyphicon glyphicon-plus" style="padding-right:5px" aria-hidden="true"></span>@Localizer["Create New"]
                </a>
            </h1>
            <hr>
            <p class="text-danger">@ViewData["ErrorMessage"]</p>
            <table class="table table-bordered table-hover">
                <thead class="thead-default">
                    <tr>
                        <th class="text-center col-md-3">@Localizer["Id"]</th>
                        <th class="text-center col-md-6">@Localizer["Name"]</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="text-right">@item.Id</td>
                            <td class="text-left">@item.Name</td>
                            <td class="text-left">
                                <a class="btn btn-primary"
                                   asp-action="Edit"
                                   asp-controller="CityManagement"
                                   asp-route-id=@item.Id>
                                    @Localizer["Edit"]
                                </a>
                                <a class="btn btn-primary open-deletionDialog"
                                   href="#"
                                   data-toggle="modal"
                                   data-target="#myModal"
                                   data-index="@item.Id"
                                   data-cityId="@item.Id"
                                   data-cityName="@item.Name">
                                    @Localizer["Delete"]
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </row>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">@Localizer["Deletion"]</h4>
            </div>
            <div class="modal-body" style="padding-left:30px">
                <p>
                    <h4>@Localizer["Are you sure you want to delete this item?"] </h4>
                    <b>@Localizer["Id"] : </b> <span id="cityid"></span> <br>
                    <b>@Localizer["Name"] : </b> <span id="cityname"></span>
                </p>
            </div>
            <div class="modal-footer">
                <form asp-action="Delete" asp-controller="CityManagement">
                    <input class="yes-delete" type="hidden" name="Id" />
                    <button type="submit" class="btn btn-primary">
                        @Localizer["Yes, delete!"]
                    </button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">
                        @Localizer["Close"]
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>