TicketReseller/TicketReseller.WebUI/Areas/Admin/Controllers/VenueManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TicketReseller.Data.Context;
using TicketReseller.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TicketReseller.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class VenueManagementController : Controller
    {
        private UnitOfWork _unitOfWork;
        private readonly IStringLocalizer<VenueManagementController> localizer;

        public VenueManagementController(IStringLocalizer<VenueManagementController> localizer, UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            this.localizer = localizer;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var venues = _unitOfWork.VenueRepository.Get();
            return View(venues);
        }

        public ActionResult Create()
        {
            PopulateCitiesDropDownList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Venue venue)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _unitOfWork.VenueRepository.Insert(venue);
                    _unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DbUpdateException /* dex */)
            {
                ModelState.AddModelError(string.Empty, localizer["Unable to save changes. Try again, and if the problem persists contact your system administrator."]);
            }
            return View(venue);
        }

        public ActionResult Edit(int id)
        {
            var venue = _unitOfWork.VenueRepository.GetByID(id);

            if (venue == null)
            {
                return RedirectToAction("Index");
            }

            PopulateCitiesDropDownList(venue.CityId);

            return View(venue);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Venue venue)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _unitOfWork.VenueRepository.Update(venue);
                    _unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DbUpdateException /* dex */)
            {
                ModelState.AddModelError(string.Empty, localizer["Unable to save changes. Try again, and if the problem persists contact your system administrator."]);
            }
            return View(venue);
        }

        private void PopulateCitiesDropDownList(object selectedCity = null)
        {
            var cities = _unitOfWork.CityRepository.Get(orderBy: q => q.OrderBy(d => d.Name));
            ViewBag.Cities = new SelectList(cities, "Id", "Name", selectedCity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                var venue = _unitOfWork.VenueRepository.GetByID(id);

                if (venue == null)
                {
                    return RedirectToAction("Index");
                }
                _unitOfWork.VenueRepository.Delete(id);
                _unitOfWork.Save();
            }
            catch (DbUpdateException /* dex */)
            {
                ViewData["ErrorMessage"] =
                    localizer["Delete failed. Try again, and if the problem persists " +
                    "see your system administrator."];
            }
            return RedirectToAction("Index");
        }

    }
}

TicketReseller/TicketReseller.WebUI/Areas/Admin/Views/VenueManagement/Create.cshtml
@model Venue
@{
    ViewData["Title"] = "Create";
}
@section OptionsSideMenu {
    <div class="col-md-3">
        @{await Html.RenderPartialAsync("_AdminOptionsPartial");}
    </div>
}
<div class="col-md-6">
    <h2>@Localizer["Creation venue"]</h2>
    <hr />
    <p class="text-danger">@ViewData["ErrorMessage"]</p>
    <form asp-action="Create">
        <div class="form-horizontal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Address" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="City" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <select asp-for="CityId" class="form-control" asp-items="ViewBag.Cities">
                        <option value="">-- @Localizer["Select City"] --</option>
                    </select>
                    <span asp-validation-for="CityId" class="text-danger"></span>
                </div>
            </div>
            </br>
            <div class="form-group pull-right">
                <div class="col-md-10">
                    <input type="submit" value="@Localizer["Create"]" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </form>
    <div>
        <a asp-action="Index">@Localizer["Back to List"]</a>
    </div>
</div>
@section Scripts {
@{await Html.RenderPartialAsync("/Areas/Main/Views/Shared/_ValidationScriptsPartial.cshtml");}
}

TicketReseller/TicketReseller.WebUI/Areas/Admin/Views/VenueManagement/Edit.cshtml
@model Venue
@{
    ViewData["Title"] = "Edit";
}
@section OptionsSideMenu {
    <div class="col-md-3">
        @{await Html.RenderPartialAsync("_AdminOptionsPartial");}
    </div>
}
<div class="col-md-6">
    <h2>@Localizer["Editing venue"]</h2>
    <hr />
    <p class="text-danger">@ViewData["ErrorMessage"]</p>
    <form asp-action="Edit">
        <div class="form-horizontal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Address" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="City" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <select asp-for="CityId" class="form-control" asp-items="ViewBag.Cities">
                        <option value="">-- @Localizer["Select City"] --</option>
                    </select>
                    <span asp-validation-for="CityId" class="text-danger"></span>
                </div>
            </div>
            </br>
            <div class="form-group pull-right">
                <div class="col-md-10">
                    <input type="submit" value="@Localizer["Update"]" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </form>
    <div>
        <a asp-action="Index">@Localizer["Back to List"]</a>
    </div>
</div>
@section Scripts {
@{await Html.RenderPartialAsync("/Areas/Main/Views/Shared/_ValidationScriptsPartial.cshtml");}
}

TicketReseller/TicketReseller.WebUI/Areas/Admin/Views/VenueManagement/Index.cshtml
@model List<Venue>
@section OptionsSideMenu {
    <div class="col-md-3">
        @{await Html.RenderPartialAsync("_AdminOptionsPartial");}
    </div>
}
<div class="col-md-9">
    <row>
        <div class="col-md-12">
            <h1>
                <small>@Localizer["Venues"]</small>

                <a class="btn btn-primary pull-right" role="button" asp-action="Create" asp-controller="VenueManagement">
                    <span class="glyphicon glyphicon-plus" style="padding-right:5px" aria-hidden="true"></span>@Localizer["Create New"]
                </a>
            </h1>
            <hr>
            <p class="text-danger">@ViewData["ErrorMessage"]</p>
            <table class="table table-bordered table-hover">
                <thead class="thead-default">
                    <tr>
                        <th class="text-center">@Localizer["Id"]</th>
                        <th class="text-center">@Localizer["Name"]</th>
                        <th class="text-center">@Localizer["City"]</th>
                        <th class="text-center">@Localizer["Address"]</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="text-right">@item.Id</td>
                            <td class="text-left">@item.Name</td>
                            <td class="text-left">@item.City.Name</td>
                            <td class="text-left">@item.Address</td>
                            <td class="text-left">
                                <a class="btn btn-primary"
                                   asp-action="Edit"
                                   asp-controller="VenueManagement"
                                   asp-route-id=@item.Id>
                                    @Localizer["Edit"]
                                </a>
                                <a class="btn btn-primary open-deletionDialog"
                                   href="#"
                                   data-toggle="modal"
                                   data-target="#myModal"
                                   data-index="@item.Id"
                                   data-venueId="@item.Id"
                                   data-venueName="@item.Name"
                                   data-venueCity="@item.City.Name"
                                   data-venueAddress="@item.Address">
                                    @Localizer["Delete"]
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </row>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">@Localizer["Deletion"]</h4>
            </div>
            <div class="modal-body" style="padding-left:30px">
                <p>
                    <h4>@Localizer["Are you sure you want to delete this item?"] </h4>
                    <b>@Localizer["Id"] : </b> <span id="venueid"></span> <br>
                    <b>@Localizer["Name"] : </b> <span id="venuename"></span> <br>
                    <b>@Localizer["City"] : </b> <span id="venuecity"></span> <br>
                    <b>@Localizer["Address"] : </b> <span id="venueaddress"></span>
                </p>
            </div>
            <div class="modal-footer">
                <form asp-action="Delete" asp-controller="VenueManagement">
                    <input class="yes-delete" type="hidden" name="Id" />
                    <button type="submit" class="btn btn-primary">
                        @Localizer["Yes, delete!"]
                    </button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">
                        @Localizer["Close"]
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>