TicketReseller/TicketReseller.WebUI/Areas/Admin/Controllers/RoleManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TicketReseller.Data.Context;
using TicketReseller.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using Microsoft.AspNetCore.Authorization;
using AutoMapper;
using TicketReseller.WebUI.Areas.Admin.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TicketReseller.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class RoleManagementController : Controller
    {
        private UnitOfWork _unitOfWork;
        private IMapper _mapper;
        private readonly IStringLocalizer<RoleManagementController> localizer;

        public RoleManagementController(IStringLocalizer<RoleManagementController> localizer,
            IMapper mapper, UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            this.localizer = localizer;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View(_mapper.Map<List<UserViewModel>>(_unitOfWork.UserRepository.Get()));
        }

        public ActionResult Edit(int id)
        {
            var user = _unitOfWork.UserRepository.GetByID(id);

            if (user == null)
            {
                return RedirectToAction("Index");
            }
            return View(_mapper.Map<UserViewModel>(user));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserViewModel userViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = _unitOfWork.UserRepository.GetByID(userViewModel.Id);
                    user.RoleId = userViewModel.RoleId;
                    _unitOfWork.UserRepository.Update(user);
                    _unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DbUpdateException /* dex */)
            {
                ModelState.AddModelError(string.Empty, localizer["Unable to save changes. Try again, and if the problem persists contact your system administrator."]);
            }
            return View(userViewModel);
        }
    }
}

TicketReseller/TicketReseller.WebUI/Areas/Admin/Views/RoleManagement/Edit.cshtml
@model UserViewModel
@{
    ViewData["Title"] = "Edit";
}
@section OptionsSideMenu {
    <div class="col-md-3">
        @{await Html.RenderPartialAsync("_AdminOptionsPartial");}
    </div>
}
<div class="col-md-6">
    <h2>@Localizer["Editing user"]</h2>
    <hr />
    <p class="text-danger">@ViewData["ErrorMessage"]</p>
    <form asp-action="Edit">
        <div class="form-horizontal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="col-md-3 control-label"></label>
                <div class="col-md-9">
                    <label class="control-label nonebold">@Model.Email</label>
                    <input asp-for="Email" hidden class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="col-md-3 control-label"></label>
                <div class="col-md-9">
                    <label class="control-label nonebold">@Model.FirstName</label>
                    <input asp-for="FirstName" hidden class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="col-md-3 control-label"></label>
                <div class="col-md-9">
                    <label class="control-label nonebold">@Model.LastName</label>
                    <input asp-for="LastName" hidden class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="col-md-3 control-label"></label>
                <div class="col-md-9">
                    <label class="control-label nonebold">@Model.Address</label>
                    <input asp-for="Address" hidden class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="col-md-3 control-label"></label>
                <div class="col-md-9">
                    <label class="control-label nonebold">@Model.PhoneNumber</label>
                    <input asp-for="PhoneNumber" hidden class="form-control" />
                </div>
            </div>
            <div class="form-group">                
                    <label asp-for="RoleId" class="col-md-3 control-label"></label>
                <div class="col-md-6">
                    <select class="form-control" asp-for="RoleId" asp-items="Html.GetEnumSelectList<UserRole>()"></select>
                    <span asp-validation-for="RoleId" class="text-danger"></span>
                </div>
            </div>
        </div>
        </br>
        <div class="form-group">
            <div class="col-md-5 pull-right">
                <input type="submit" value="@Localizer["Update"]" class="btn btn-primary" />
            </div>
        </div>
    </form>
    <div>
        <a asp-action="Index">@Localizer["Back to List"]</a>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("/Areas/Main/Views/Shared/_ValidationScriptsPartial.cshtml");}
}

TicketReseller/TicketReseller.WebUI/Areas/Admin/Views/RoleManagement/Index.cshtml
@model List<UserViewModel>

@section OptionsSideMenu {
    <div class="col-md-3">
        @{await Html.RenderPartialAsync("_AdminOptionsPartial");}
    </div>
}
<div class="col-md-9">
    <row>
        <div class="col-md-12">
            <h1>
                <small>@Localizer["Roles"]</small>
            </h1>
            <hr>
            <p class="text-danger">@ViewData["ErrorMessage"]</p>
            <table class="table table-bordered table-hover">
                <thead class="thead-default">
                    <tr>
                        <th rowspan="2" class="text-right">@Localizer["Id"]</th>
                        <th class="text-left">@Localizer["Email"]</th>                       
                        <th class="text-left">@Localizer["Address"]</th>
                        <th rowspan="2" class="text-center">@Localizer["Role"]</th>
                        
                    </tr>
                    <tr>
                        <th class="text-left">@Localizer["Name"]</th>
                        <th class="text-left">@Localizer["Phone number"]</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td rowspan="2" class="text-right">@item.Id</td>
                            <td class="text-left">@item.Email</td>
                            <td class="text-left">@item.Address</td>
                            <td rowspan="2" class="text-center">
                                @item.RoleId
                            </td>

                            <td class="text-left" rowspan="2">
                                <a class="btn btn-primary"
                                   asp-action="Edit"
                                   asp-controller="RoleManagement"
                                   asp-route-id=@item.Id>
                                    @Localizer["Edit"]
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-left">@item.FirstName @item.LastName</td>
                            <td class="text-left">@item.PhoneNumber</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </row>
</div>