TicketReseller/TicketReseller.WebUI/Areas/Admin/Controllers/PerfomanceManagementController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TicketReseller.Data.Context;
using TicketReseller.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Localization;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TicketReseller.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class PerfomanceManagementController : Controller
    {
        private UnitOfWork _unitOfWork;
        private IHostingEnvironment _appEnvironment;
        private readonly IStringLocalizer<PerfomanceManagementController> localizer;

        public PerfomanceManagementController(IStringLocalizer<PerfomanceManagementController> localizer, UnitOfWork unitOfWork, IHostingEnvironment appEnvironment)
        {
            _unitOfWork = unitOfWork;
            _appEnvironment = appEnvironment;
            this.localizer = localizer;

        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            var perfomances = _unitOfWork.PerfomanceRepository.Get();
            return View(perfomances);
        }

        public ActionResult Create()
        {
            PopulateVenuesDropDownList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Perfomance perfomance, IFormFile uploadedFile)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (uploadedFile != null)
                    {
                        string path = "/Images/" + uploadedFile.FileName;
                        using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                        {
                            await uploadedFile.CopyToAsync(fileStream);
                        }

                        perfomance.Image = path;
                        _unitOfWork.PerfomanceRepository.Insert(perfomance);
                        _unitOfWork.Save();
                        return RedirectToAction("Index");
                    }
                }
            }
            catch (DbUpdateException /* dex */)
            {
                ModelState.AddModelError(string.Empty, localizer["Unable to save changes. Try again, and if the problem persists contact your system administrator."]);
            }

            PopulateVenuesDropDownList();
            return View(perfomance);
        }

        public ActionResult Edit(int id)
        {
            var perfomance = _unitOfWork.PerfomanceRepository.GetByID(id);

            if (perfomance == null)
            {
                return RedirectToAction("Index");
            }

            PopulateVenuesDropDownList(perfomance.VenueId);

            return View(perfomance);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Perfomance perfomance, IFormFile uploadedFile)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (uploadedFile != null)
                    {
                        string path = "/Images/" + uploadedFile.FileName;
                        using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                        {
                            await uploadedFile.CopyToAsync(fileStream);
                        }

                        perfomance.Image = path;
                    }
                    _unitOfWork.PerfomanceRepository.Update(perfomance);
                    _unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DbUpdateException /* dex */)
            {
                ModelState.AddModelError(string.Empty, localizer["Unable to save changes. Try again, and if the problem persists contact your system administrator."]);
            }

            PopulateVenuesDropDownList(perfomance.VenueId);
            return View(perfomance);
        }

        private void PopulateVenuesDropDownList(object selectedVenue = null)
        {
            var venues = _unitOfWork.VenueRepository.Get(orderBy: q => q.OrderBy(d => d.Name));
            ViewBag.Venues = new SelectList(venues, "Id", "Name", selectedVenue);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                var perfomance = _unitOfWork.PerfomanceRepository.GetByID(id);

                if (perfomance == null)
                {
                    return RedirectToAction("Index");
                }
                _unitOfWork.PerfomanceRepository.Delete(id);
                _unitOfWork.Save();
            }
            catch (DbUpdateException /* dex */)
            {
                ViewData["ErrorMessage"] =
                    localizer["Delete failed. Try again, and if the problem persists " +
                    "see your system administrator."];
            }
            return RedirectToAction("Index");
        }

    }
}

TicketReseller/TicketReseller.WebUI/Areas/Admin/Views/PerfomanceManagement/Create.cshtml
@model Perfomance
@{
    ViewData["Title"] = "Create";
}
@section OptionsSideMenu {
    <div class="col-md-3">
        @{await Html.RenderPartialAsync("_AdminOptionsPartial");}
    </div>
}
<div class="col-md-6">
    <h2>@Localizer["Creation perfomance"]</h2>
    <hr />
    <p class="text-danger">@ViewData["ErrorMessage"]</p>
    <form asp-action="Create" enctype="multipart/form-data">
        <div class="form-horizontal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Date" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Date" data-provide="datepicker" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Venue" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <select asp-for="VenueId" class="form-control" asp-items="ViewBag.Venues">
                        <option value="">-- @Localizer["Select Venue"] --</option>
                    </select>
                    <span asp-validation-for="VenueId" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Image" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input class="input-image" type="file" name="uploadedFile" />
                    <input class="input-image" type="hidden" asp-for="Image" />
                    <span asp-validation-for="Image" class="text-danger"></span><br>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>

            </br>
            <div class="form-group pull-right">
                <div class="col-md-10">
                    <input id="submit-perfomance" type="submit" value="@Localizer["Create"]" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </form>
    <div>
        <a asp-action="Index">@Localizer["Back to List"]</a>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("/Areas/Main/Views/Shared/_ValidationScriptsPartial.cshtml");}
}

TicketReseller/TicketReseller.WebUI/Areas/Admin/Views/PerfomanceManagement/Edit.cshtml
@model Perfomance
@{
    ViewData["Title"] = "Edit";
}
@section OptionsSideMenu {
    <div class="col-md-3">
        @{await Html.RenderPartialAsync("_AdminOptionsPartial");}
    </div>
}
<div class="col-md-6">
    <h2>@Localizer["Editing perfomance"]</h2>
    <hr />
    <p class="text-danger">@ViewData["ErrorMessage"]</p>
    <form asp-action="Edit"  enctype="multipart/form-data">
        <div class="form-horizontal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Date" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Date" data-provide="datepicker" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Venue" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <select asp-for="VenueId" class="form-control" asp-items="ViewBag.Venues">
                        <option value="">-- @Localizer["Select Venue"] --</option>
                    </select>
                    <span asp-validation-for="VenueId" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Image" class="col-md-2 control-label"></label>
                <div class="col-md-6">
                    <img class="img-responsive roundCorner" src="@Model.Image" alt="">
                    <br>
                </div>
                
                <div class="col-md-10 pull-right">
                    <input class="input-image" type="file" name="uploadedFile" />
                    <input class="input-image" type="hidden" asp-for="Image" />
                    <span asp-validation-for="Image" class="text-danger"></span><br>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>

            </br>
            <div class="form-group pull-right">
                <div class="col-md-10">
                    <input type="submit" value="@Localizer["Update"]" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </form>
    <div>
        <a asp-action="Index">@Localizer["Back to List"]</a>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("/Areas/Main/Views/Shared/_ValidationScriptsPartial.cshtml");}
}

TicketReseller/TicketReseller.WebUI/Areas/Admin/Views/PerfomanceManagement/Index.cshtml
@model List<Perfomance>
@section OptionsSideMenu {
    <div class="col-md-3">
        @{await Html.RenderPartialAsync("_AdminOptionsPartial");}
    </div>
}
<div class="col-md-9">
    <row>
        <div class="col-md-12">
            <h1>
                <small>@Localizer["Perfomances"]</small>
                <a class="btn btn-primary pull-right" role="button" asp-action="Create" asp-controller="PerfomanceManagement">
                    <span class="glyphicon glyphicon-plus" style="padding-right:5px" aria-hidden="true"></span>@Localizer["Create New"]
                </a>
            </h1>
            <hr>
            <p class="text-danger">@ViewData["ErrorMessage"]</p>
            <table class="table table-bordered table-hover">
                <thead class="thead-default">
                    <tr>
                        <th class="text-center col-md-2" style="padding-bottom:30px" rowspan="2">@Localizer["Image"]</th>
                        <th class="text-center col-md-1">@Localizer["Id"]</th>
                        <th class="text-center col-md-3">@Localizer["Name"]</th>
                        <th class="text-center col-md-2">@Localizer["Date"]</th>
                        <th class="text-center col-md-2">@Localizer["Venue"]</th>
                    </tr>
                    <tr>
                        <th class="text-center" colspan="4">@Localizer["Description"]</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td rowspan="2" style="padding:0px">
                                <img class="img-responsive" src="@item.Image" alt="">
                            </td>
                            <td class="text-right">@item.Id</td>
                            <td class="text-left">@item.Name</td>
                            <td class="text-center">@item.Date.ToString("d", HandlingFormat.GetFormatDate())</td>
                            <td class="text-left">@item.Venue.Name</td>
                            <td class="text-left" rowspan="2" style="padding-top:20px">
                                <a class="btn btn-primary"
                                   asp-action="Edit"
                                   asp-controller="PerfomanceManagement"
                                   asp-route-id=@item.Id>
                                    @Localizer["Edit"]
                                </a>
                                <a class="btn btn-primary open-deletionDialog"
                                   href="#"
                                   data-toggle="modal"
                                   data-target="#myModal"
                                   data-index="@item.Id"
                                   data-perfomanceId="@item.Id"
                                   data-perfomanceName="@item.Name"
                                   data-perfomanceDate="@item.Date.ToString("d",HandlingFormat.GetFormatDate())"
                                   data-perfomanceVenue="@item.Venue.Name"
                                   data-perfomanceDescription="@item.Description">
                                    @Localizer["Delete"]
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-left" colspan="4">@item.Description</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </row>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">@Localizer["Deletion"]</h4>
            </div>
            <div class="modal-body" style="padding-left:30px">
                <p>
                    <h4>@Localizer["Are you sure you want to delete this item? "]</h4>
                    <b>@Localizer["Id"] : </b> <span id="perfomanceid"></span> <br>
                    <b>@Localizer["Name"] : </b> <span id="perfomancename"></span> <br>
                    <b>@Localizer["Date"] : </b> <span id="perfomancedate"></span> <br>
                    <b>@Localizer["Venue"] : </b> <span id="perfomancevenue"></span> <br>
                    <b>@Localizer["Description"] : </b> <span id="perfomancedescription"></span>
                </p>
            </div>
            <div class="modal-footer">
                <form asp-action="Delete" asp-controller="PerfomanceManagement">
                    <input class="yes-delete" type="hidden" name="Id" />
                    <button type="submit" class="btn btn-primary">
                        @Localizer["Yes, delete!"]
                    </button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">
                        @Localizer["Close"]
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>